[package]
name = "sylos"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.39", features=["std"]}
nom = "7"
serde = "1.0.218"
tokio = {version = "1.43.0", features = ["full"]}
